# Experiment configuration
experiment:
  name: Transformer_Dueling_DDQN_FOMDP
  model_dir: models
  model_name: POMDP
  result_dir: results
  result_name: POMDP


# Training configuration
train:
  seeds: [12, 34, 56, 78, 90]
  batch_size: 1
  learning_rate: 0.0005
  optimizer: rms_prop
  max_gradient_norm: inf
  n_warmup_batches: 5
  update_target_every_steps: 10
  tau: 0.1

# Network configuration
network:
  seq_len: 1
  in_dim: 1
  num_layers: 1

# Environment configuration
env:
  version: v0
  mdp: POMDP
  render: False

# Agent configuration
agent:
  gamma: 1.00
  max_minutes: 2000
  max_episodes: 300
  goal_mean_100_reward: 475

# Strategy configuration
strategy:
  init_epsilon: 1.0
  min_epsilon: 0.3
  decay_steps: 20000