# Training configuration
train:
  seeds: [12, 34, 56, 78, 90]
  batch_size: 8
  seq_len: 64
  learning_rate: 5e-4
  optimizer: adam
  max_gradient_norm: inf
  n_warmup_batches: 2
  update_target_every_steps: 1
  tau: 0.1
  random_sample: False

# Network configuration
network:
  model: transformer_dueling_ddqn
  net_type: transformer
  in_dim: 64
  num_layers: 1
  memory_len: 64

# Environment configuration
env:
  version: v1
  mdp: POMDP
  render: False

# Agent configuration
agent:
  gamma: 0.99
  max_minutes: 40
  max_episodes: 1000
  goal_mean_100_reward: 475

# Strategy configuration
strategy:
  init_epsilon: 1.0
  min_epsilon: 0.3
  decay_steps: 20000